services:
  traefik:
    image: traefik:v3.0
    container_name: traefik
    restart: unless-stopped
    command:
      - --api.dashboard=true
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
    ports:
      - "80:80"
      - "8080:8080" # Traefik dashboard
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - smartcities_net

  postgres:
    image: postgres:16
    container_name: postgres_db
    restart: unless-stopped
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d
    networks:
      - smartcities_net

  backend:
    image: ghcr.io/thesynus/smartcities-backend:latest
    container_name: smartcities_backend
    restart: unless-stopped
    env_file: .env
    depends_on:
      - postgres
    networks:
      - smartcities_net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=Host(`api.${TRAEFIK_DOMAIN}`)"
      - "traefik.http.services.backend.loadbalancer.server.port=3001"

  frontend:
    image: ghcr.io/thesynus/smartcities-frontend:latest
    container_name: smartcities_frontend
    restart: unless-stopped
    networks:
      - smartcities_net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`${TRAEFIK_DOMAIN}`)"
      - "traefik.http.services.frontend.loadbalancer.server.port=80"

volumes:
  postgres_data:

networks:
  smartcities_net:
    driver: bridge
