services:
  postgres:
    image: postgres
    container_name: postgres_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: Admin!1234
      POSTGRES_DB: webportal
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - postgres_run:/var/run/postgresql
      - ./db:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    container_name: postgres_admin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin123
      PGADMIN_CONFIG_SERVER_MODE: 'False'
      PGADMIN_SERVER_JSON_FILE: /pgadmin4/servers.json
    ports:
      - "8080:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
      - ./db/servers.json:/pgadmin4/servers.json
    depends_on:
      - postgres

  api:
    build: ./api
    container_name: node_api
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=webportal
      - DB_USER=admin
      - DB_PASSWORD=Admin!1234
      - PORT=3000
    depends_on:
      - postgres

volumes:
  postgres_data:
  postgres_run:
  pgadmin_data: